---
title: Research
---

## Consumers Preferences over Retail Channels: Evidence from Emergency Contraceptives

<a href="" target="_blank">Working Paper</a>

I study the preferences of consumers over different retail channels (drug stores, mass merchandiser, or grocery stores) for purchasing over-the-counter emergency contraceptives (EC). Using monthly EC sales in Texas from 2017 to 2019, I estimate consumer preferences using a BLP discrete choice model. My results show that consumers are sensitive to prices, and that they exhibit preferences for specific retail channels but not for branded vs generic products. To address recent policy debates, I conduct counterfactual simulations banning the sale of EC from grocery or mass merchandiser stores. I find that this would result in 5-8% increase in the number of consumers who do not buy EC.

----

## Externalities of Marijuana Legalization: Marijuana Use in Non-Legalizing States
with Elaine Liu and Marit Hinnosaar

<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4571391" target="_blank">Published in SSRN</a>

We study the impact of distant connections on marijuana use. Using data on Facebook friendships, we investigate whether connections to states where recreational marijuana is legalized affect marijuana use in areas where it remains illegal. We find that areas more connected to legalized states have a larger increase in marijuana use. These results indicate that even non-local connections can impact behavior. Our findings suggest that studies measuring the impact of marijuana legalization using a standard difference-in-differences approach, without accounting for the network, underestimate the direct effect on the state that legalized.

